# Generated by Django 4.1.7 on 2023-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='Ваш никнейм'),
        ),
    ]
